### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by thefill** [esp-rs/esp-web-flash-server#3]
Hi there,
just tried to to execute install-rust-toolchain.sh and found out that a dep. on your package is breaking the build - output below:

```
$ Installing web-flash v0.1.0 (https://github.com/bjoernQ/esp-web-flash-server#946047a5)
$   Updating crates.io index
$   Updating git repository `https://github.com/esp-rs/espflash`
$ error: failed to compile `web-flash v0.1.0 (https://github.com/bjoernQ/esp-web-flash-server#946047a5)`, intermediate artifacts can be found at `/tmp/cargo-installBPdfpO`
$ Caused by:
$ failed to get `espflash` as a dependency of package `web-flash v0.1.0 (/home/esp/.cargo/git/checkouts/esp-web-flash-server-033e701f302416a2/946047a)`
$ Caused by:
$   failed to load source for dependency `espflash`
$ Caused by:
$   Unable to update https://github.com/esp-rs/espflash?branch=bugfix/chip-name-esptool
$ Caused by:
$   failed to find branch "bugfix/chip-name-esptool"
```

Looks like the branch "bugfix/chip-name-esptool" is gone for "espflash". If you can explain what was the purpose of using a bugfix branch as a dep, I can create a PR.

**Comment by bjoernQ** [comment]
Thanks for opening this issue. That branch wasn't merged at the time of initial development of this tool and somehow it was just forgotten.

Ideally we should use espflash from crates.io

**Comment by thefill** [comment]
@bjoernQ yeah I know - just tried to play around to with version 1.7.0 and realised it does not even have a struct like "FirmwareImageBuilder". I would love to help but not sure I can grasp this - kinda exceeds my embedded rust skills. I'm still more than happy to try with your guide unless you want to step in ;-)

**Comment by bjoernQ** [comment]
Wow - I wasn't aware of that. Apparently there is no quick fix currently - need to look into that tomorrow
I think also https://github.com/MabezDev/wokwi-server currently runs into the same issue?

**Comment by thefill** [comment]
> Wow - I wasn't aware of that. Apparently there is no quick fix currently - need to look into that tomorrow

Yeah, whole interface is diff. Would love to help but think thats beyond a simple fix :-) Poke me if I can be of any help.

> I think also https://github.com/MabezDev/wokwi-server currently runs into the same issue?
thats the thing - this one does not fail surprisingly. Just used in my dockerfile:

```
RUN chmod a+x ${INSTALL_RUST_TOOLCHAIN} \
    && ./${INSTALL_RUST_TOOLCHAIN} \
    --extra-crates "ldproxy cargo-espflash wokwi-server" \
    --export-file /home/${CONTAINER_USER}/export-esp.sh \
    --esp-idf-version "${ESP_IDF_VERSION}" \
    --minified-esp-idf "YES" \
    --build-target "${ESP_BOARD}" \
    && rustup component add clippy rustfmt
```

And all went well.

Its quite weird - checked "wokwi-server" and they use:
`espflash = { version = "1.5.2-dev", git = "https://github.com/esp-rs/espflash" }`
